baseURL: "https://blog.rifhanakram.com/"
languageCode: "en-us"
title: "Thoughts of Rifhan"
theme: "anubis"
paginate: 10
disqusShortname: blog-rifhanakram
googleAnalytics: UA-123-45
env: production

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Rifhan Akram"
  description: ""
  images:
    - images/og-featured.png
  customCSS:
    - css/my.css
  dateFormat: "2006-01-02"